// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: viewmatrix.proto
#ifndef GRPC_viewmatrix_2eproto__INCLUDED
#define GRPC_viewmatrix_2eproto__INCLUDED

#include "viewmatrix.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace viewmatrix {

class ViewTrans final {
 public:
  static constexpr char const* service_full_name() {
    return "viewmatrix.ViewTrans";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetViewMatrix(::grpc::ClientContext* context, const ::viewmatrix::Request& request, ::viewmatrix::Matrix* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::viewmatrix::Matrix>> AsyncGetViewMatrix(::grpc::ClientContext* context, const ::viewmatrix::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::viewmatrix::Matrix>>(AsyncGetViewMatrixRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::viewmatrix::Matrix>> PrepareAsyncGetViewMatrix(::grpc::ClientContext* context, const ::viewmatrix::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::viewmatrix::Matrix>>(PrepareAsyncGetViewMatrixRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void GetViewMatrix(::grpc::ClientContext* context, const ::viewmatrix::Request* request, ::viewmatrix::Matrix* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetViewMatrix(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::viewmatrix::Matrix* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void GetViewMatrix(::grpc::ClientContext* context, const ::viewmatrix::Request* request, ::viewmatrix::Matrix* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void GetViewMatrix(::grpc::ClientContext* context, const ::viewmatrix::Request* request, ::viewmatrix::Matrix* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void GetViewMatrix(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::viewmatrix::Matrix* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void GetViewMatrix(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::viewmatrix::Matrix* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::viewmatrix::Matrix>* AsyncGetViewMatrixRaw(::grpc::ClientContext* context, const ::viewmatrix::Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::viewmatrix::Matrix>* PrepareAsyncGetViewMatrixRaw(::grpc::ClientContext* context, const ::viewmatrix::Request& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status GetViewMatrix(::grpc::ClientContext* context, const ::viewmatrix::Request& request, ::viewmatrix::Matrix* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::viewmatrix::Matrix>> AsyncGetViewMatrix(::grpc::ClientContext* context, const ::viewmatrix::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::viewmatrix::Matrix>>(AsyncGetViewMatrixRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::viewmatrix::Matrix>> PrepareAsyncGetViewMatrix(::grpc::ClientContext* context, const ::viewmatrix::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::viewmatrix::Matrix>>(PrepareAsyncGetViewMatrixRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void GetViewMatrix(::grpc::ClientContext* context, const ::viewmatrix::Request* request, ::viewmatrix::Matrix* response, std::function<void(::grpc::Status)>) override;
      void GetViewMatrix(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::viewmatrix::Matrix* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void GetViewMatrix(::grpc::ClientContext* context, const ::viewmatrix::Request* request, ::viewmatrix::Matrix* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void GetViewMatrix(::grpc::ClientContext* context, const ::viewmatrix::Request* request, ::viewmatrix::Matrix* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void GetViewMatrix(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::viewmatrix::Matrix* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void GetViewMatrix(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::viewmatrix::Matrix* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::viewmatrix::Matrix>* AsyncGetViewMatrixRaw(::grpc::ClientContext* context, const ::viewmatrix::Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::viewmatrix::Matrix>* PrepareAsyncGetViewMatrixRaw(::grpc::ClientContext* context, const ::viewmatrix::Request& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetViewMatrix_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetViewMatrix(::grpc::ServerContext* context, const ::viewmatrix::Request* request, ::viewmatrix::Matrix* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetViewMatrix : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetViewMatrix() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetViewMatrix() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetViewMatrix(::grpc::ServerContext* /*context*/, const ::viewmatrix::Request* /*request*/, ::viewmatrix::Matrix* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetViewMatrix(::grpc::ServerContext* context, ::viewmatrix::Request* request, ::grpc::ServerAsyncResponseWriter< ::viewmatrix::Matrix>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetViewMatrix<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_GetViewMatrix : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_GetViewMatrix() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::viewmatrix::Request, ::viewmatrix::Matrix>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::viewmatrix::Request* request, ::viewmatrix::Matrix* response) { return this->GetViewMatrix(context, request, response); }));}
    void SetMessageAllocatorFor_GetViewMatrix(
        ::grpc::experimental::MessageAllocator< ::viewmatrix::Request, ::viewmatrix::Matrix>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::viewmatrix::Request, ::viewmatrix::Matrix>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_GetViewMatrix() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetViewMatrix(::grpc::ServerContext* /*context*/, const ::viewmatrix::Request* /*request*/, ::viewmatrix::Matrix* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* GetViewMatrix(
      ::grpc::CallbackServerContext* /*context*/, const ::viewmatrix::Request* /*request*/, ::viewmatrix::Matrix* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* GetViewMatrix(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::viewmatrix::Request* /*request*/, ::viewmatrix::Matrix* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_GetViewMatrix<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_GetViewMatrix<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetViewMatrix : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetViewMatrix() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetViewMatrix() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetViewMatrix(::grpc::ServerContext* /*context*/, const ::viewmatrix::Request* /*request*/, ::viewmatrix::Matrix* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetViewMatrix : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetViewMatrix() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetViewMatrix() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetViewMatrix(::grpc::ServerContext* /*context*/, const ::viewmatrix::Request* /*request*/, ::viewmatrix::Matrix* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetViewMatrix(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_GetViewMatrix : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_GetViewMatrix() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetViewMatrix(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_GetViewMatrix() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetViewMatrix(::grpc::ServerContext* /*context*/, const ::viewmatrix::Request* /*request*/, ::viewmatrix::Matrix* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* GetViewMatrix(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* GetViewMatrix(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetViewMatrix : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetViewMatrix() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::viewmatrix::Request, ::viewmatrix::Matrix>(std::bind(&WithStreamedUnaryMethod_GetViewMatrix<BaseClass>::StreamedGetViewMatrix, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_GetViewMatrix() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetViewMatrix(::grpc::ServerContext* /*context*/, const ::viewmatrix::Request* /*request*/, ::viewmatrix::Matrix* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetViewMatrix(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::viewmatrix::Request,::viewmatrix::Matrix>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetViewMatrix<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetViewMatrix<Service > StreamedService;
};

}  // namespace viewmatrix


#endif  // GRPC_viewmatrix_2eproto__INCLUDED
